# Generated by Django 3.2.5 on 2021-07-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_product',
            name='cart_id',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
